<?php
// $Id: themekey_debug.install,v 1.1.2.2 2010/03/26 19:41:08 mkalkbrenner Exp $

/**
 * @file
 * Cleans up variables when unistalling  @see themekey_debug.module
 *
 * @author Markus Kalkbrenner | Cocomore AG
 *   @see http://drupal.org/user/124705
 */


/**
 * Implements hook_uninstall().
 */
function themekey_debug_uninstall() {
  // Remove variables
  db_query("DELETE FROM {variable} WHERE name LIKE 'themekey_debug_%%'");
  cache_clear_all('variables', 'cache');
}
