<?php
/**
 * @file
 * evince webservice directory A to Z listing
 *
 * provides clickable A to Z index and display of results
 *
 */

include_once(drupal_get_path('module', 'evince_dir') .'/include/evince_dir_record.inc');
drupal_add_css(drupal_get_path('module', 'evince_dir') .'/css/evince_dir.css');

/**
 * Implementation of hook_menu().
 */
function evince_dir_atoz_menu() {
  $items['evince/dir/atoz'] = array(
    'title' => 'A to Z',
    'description' => 'A to Z page.',
    'page callback' => 'evince_dir_atoz_page_atoz',
    'page arguments' => NULL,
    'access arguments' => array('access evince directory'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  $items['evince/dir/atoz/%'] = array(
    'title' => 'A to Z',
    'description' => 'A to Z page.',
    'page callback' => 'evince_dir_atoz_page_atoz',
    'page arguments' => array(3),
    'access arguments' => array('access evince directory'),
    'type' => MENU_CALLBACK,
    'weight' => 10,
  );


  $items['evince/dir/atoz/%/%'] = array(
    'title' => 'A to Z',
    'description' => 'A to Z page.',
    'page callback' => 'evince_dir_atoz_page_atoz',
    'page arguments' => array(3, 4),
    'access arguments' => array('access evince directory'),
    'type' => MENU_CALLBACK,
    'weight' => 10,
  );

  $items['evince/dir/atoz/%/%/%'] = array(
    'title' => 'A to Z',
    'description' => 'A to Z page.',
    'page callback' => 'evince_dir_display_record',
    'page arguments' => array(4, 5),
    'access arguments' => array('access evince directory'),
    'type' => MENU_CALLBACK,
    'weight' => 10,
  );


  return $items;
}

/**
 * atoz - with paging removed - (see #pg# code)
 */
function evince_dir_atoz_page_atoz($start_char = NULL, $start_record = 0) {

  foreach (range('A', 'Z') as $initial) {
	// $links[] = l($initial . ' ', 'evince/dir/atoz/'. $initial);
    $links[] = l($initial, 'evince/dir/atoz/'. $initial, array('attributes' => array('class' => 'atoz-link')));
  }
  $links = implode(' ', $links);

  if (!$start_char) {
    return $links;
  }

  $sop = 0; // controls max number of items displayed #pg# - replace 0 with limit
  $record_types = array('ascservices', 'ascserviceproviders');
  $search_text = NULL;
  $start = $start_record;
  $count = $sop;
  $url_sort = 'title';
  $sort_order = 'asc';
  $facets = array();
  $url_filters = array();
  $url_starting_with = $start_char;
  $latitude = NULL;
  $longitude = NULL;
  $radius = NULL;
  $results = evince_api_facet_search($record_types, $search_text, $start, $count, $url_sort, $sort_order, $facets, $url_filters, $url_starting_with, $latitude, $longitude, $radius);

  if ($results['status'] != 'OK') {
    if ($results['status'] == 'not configured') {
      drupal_set_message('Please '. l('configure the API', 'admin/settings/evince-api') .' first.', 'error');
    }
    else {
      drupal_set_message('Error reading results: '. $results['status'], 'warning');
    }
    return NULL;
  }
  if (empty($results['entries'])) {
    $output = $links;
    $output .= '<p>No records found for '. $start_char .'</p>';
    return $output;
  }

  $model_name = 'http://opp-links.org.uk/XMLSchema/AtomModel';
  $output_list = array();
  $type;

  foreach ($results['entries'] as $item) {
    $subitem = $item['content'][0]['child'][$model_name]['model'][0]['child'][$model_name];
    $record_id = $subitem['recordid'][0]['data'];
    $record_type = $subitem['recordtype'][0]['data'];
    $name = $item['title'];
    $summary = htmlspecialchars_decode($item['description'], ENT_QUOTES);
    $location = $item['location'];
    $contact = $item['contact'];

    if($record_type == "ascservices") {
	$type = "Service";
    } else { 
	if($record_type == "ascserviceproviders") {
	    $type = "Service Provider";
	}
    }

    $output_list[] = array(
     '#service' => "<h3>" . l($name, 'evince/dir/atoz/'. $start_char . '/' . $record_type . '/' . $record_id) . 
	"</h3>" . "<h4>" . $location . "</h4>" . "<p>" . $summary . "</p>" . "<span>" . $contact . "</span>",
     '#type' => "<span>" . $type . "</span>",
    );
  }

  $maxrecs = $results['opensearch']['totalResults'];

/* #pg# - re-instate this block replacing 3 lines following
  $nsr = $start_record + $sop;
  if ($nsr > $maxrecs)
    $next = null;
  else
    $next = l('NEXT', 'evince/dir/atoz/'. $start_char . '/' . $nsr);

  $psr = $start_record - $sop;
  if ($psr < 0)
    $prev = null;
  else
    $prev = l('PREV', 'evince/dir/atoz/'. $start_char . '/' . $psr);

  $hdrs = array('Title', 'Summary', 'Location', 'Contact');
  $output = theme('table', $hdrs, $output_list). $prev .'  ' . $next .'  (' . $maxrecs . ' records found) ' . $back;
  $output = "<div id='edart'>" . $output . '</div>';
*/

  $hdrs = array('Service/Organisation', 'Type');
  $output = $maxrecs . ' results for '. $start_char . theme('table', $hdrs, $output_list);
  $output = $links .'<div id="edart">' . $output . '</div>';

  return $output;
}

